[vps_serveurs]
# Remplacez "votre_ip_serveur" par l'adresse IP de votre VPS (ou localhost si vous testez en local)
vps_tp ansible_host=votre_ip_serveur ansible_user=votre_user_admin

[localhost]
# Pour les tests sur la machine locale si vous n'avez pas de VPS
localhost ansible_connection=local
